/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server.js']) {
  _$jscoverage['server.js'] = [];
  _$jscoverage['server.js'][1] = 0;
  _$jscoverage['server.js'][2] = 0;
  _$jscoverage['server.js'][4] = 0;
  _$jscoverage['server.js'][5] = 0;
  _$jscoverage['server.js'][6] = 0;
  _$jscoverage['server.js'][7] = 0;
  _$jscoverage['server.js'][10] = 0;
  _$jscoverage['server.js'][11] = 0;
  _$jscoverage['server.js'][14] = 0;
}
_$jscoverage['server.js'].source = ["var http = require(\"http\")","var url = require(\"url\")","","function start(route, handlers) {","\tfunction onRequest(request, response) {","\t\tvar pathname = url.parse(request.url).pathname;","\t\troute(handlers, pathname, request, response);","\t}","","\thttp.createServer(onRequest).listen(8888);","\tconsole.log(\"Server started on http://localhost:8888/\");","}","","exports.start = start;"];
_$jscoverage['server.js'][1]++;
var http = require("http");
_$jscoverage['server.js'][2]++;
var url = require("url");
_$jscoverage['server.js'][4]++;
function start(route, handlers) {
  _$jscoverage['server.js'][5]++;
  function onRequest(request, response) {
    _$jscoverage['server.js'][6]++;
    var pathname = url.parse(request.url).pathname;
    _$jscoverage['server.js'][7]++;
    route(handlers, pathname, request, response);
}
  _$jscoverage['server.js'][10]++;
  http.createServer(onRequest).listen(8888);
  _$jscoverage['server.js'][11]++;
  console.log("Server started on http://localhost:8888/");
}
_$jscoverage['server.js'][14]++;
exports.start = start;
