/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['server.js']) {
  _$jscoverage['server.js'] = [];
  _$jscoverage['server.js'][1] = 0;
  _$jscoverage['server.js'][2] = 0;
  _$jscoverage['server.js'][3] = 0;
  _$jscoverage['server.js'][5] = 0;
  _$jscoverage['server.js'][6] = 0;
  _$jscoverage['server.js'][7] = 0;
  _$jscoverage['server.js'][8] = 0;
  _$jscoverage['server.js'][11] = 0;
  _$jscoverage['server.js'][12] = 0;
  _$jscoverage['server.js'][13] = 0;
  _$jscoverage['server.js'][16] = 0;
}
_$jscoverage['server.js'].source = ["<span class=\"k\">var</span> http <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"http\"</span><span class=\"k\">)</span>","<span class=\"k\">var</span> url <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"url\"</span><span class=\"k\">)</span>","<span class=\"k\">var</span> socket_server <span class=\"k\">=</span> require<span class=\"k\">(</span><span class=\"s\">\"./socket_server\"</span><span class=\"k\">);</span>","","<span class=\"k\">function</span> start<span class=\"k\">(</span>route<span class=\"k\">,</span> handlers<span class=\"k\">)</span> <span class=\"k\">{</span>","\t<span class=\"k\">function</span> onRequest<span class=\"k\">(</span>request<span class=\"k\">,</span> response<span class=\"k\">)</span> <span class=\"k\">{</span>","\t\t<span class=\"k\">var</span> pathname <span class=\"k\">=</span> url<span class=\"k\">.</span>parse<span class=\"k\">(</span>request<span class=\"k\">.</span>url<span class=\"k\">).</span>pathname<span class=\"k\">;</span>","\t\troute<span class=\"k\">(</span>handlers<span class=\"k\">,</span> pathname<span class=\"k\">,</span> request<span class=\"k\">,</span> response<span class=\"k\">);</span>","\t<span class=\"k\">}</span>","","\t<span class=\"k\">var</span> server <span class=\"k\">=</span> http<span class=\"k\">.</span>createServer<span class=\"k\">(</span>onRequest<span class=\"k\">).</span>listen<span class=\"k\">(</span><span class=\"s\">80</span><span class=\"k\">);</span>","\tsocket_server<span class=\"k\">.</span>bind<span class=\"k\">(</span>server<span class=\"k\">);</span>","\tconsole<span class=\"k\">.</span>log<span class=\"k\">(</span><span class=\"s\">\"Server started on http://localhost/\"</span><span class=\"k\">);</span>","<span class=\"k\">}</span>","","exports<span class=\"k\">.</span>start <span class=\"k\">=</span> start<span class=\"k\">;</span>"];
_$jscoverage['server.js'][1]++;
var http = require("http");
_$jscoverage['server.js'][2]++;
var url = require("url");
_$jscoverage['server.js'][3]++;
var socket_server = require("./socket_server");
_$jscoverage['server.js'][5]++;
function start(route, handlers) {
  _$jscoverage['server.js'][6]++;
  function onRequest(request, response) {
    _$jscoverage['server.js'][7]++;
    var pathname = url.parse(request.url).pathname;
    _$jscoverage['server.js'][8]++;
    route(handlers, pathname, request, response);
}
  _$jscoverage['server.js'][11]++;
  var server = http.createServer(onRequest).listen(80);
  _$jscoverage['server.js'][12]++;
  socket_server.bind(server);
  _$jscoverage['server.js'][13]++;
  console.log("Server started on http://localhost/");
}
_$jscoverage['server.js'][16]++;
exports.start = start;
