/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['static_handler.js']) {
  _$jscoverage['static_handler.js'] = [];
  _$jscoverage['static_handler.js'][3] = 0;
  _$jscoverage['static_handler.js'][4] = 0;
  _$jscoverage['static_handler.js'][6] = 0;
  _$jscoverage['static_handler.js'][7] = 0;
  _$jscoverage['static_handler.js'][8] = 0;
  _$jscoverage['static_handler.js'][9] = 0;
  _$jscoverage['static_handler.js'][10] = 0;
  _$jscoverage['static_handler.js'][11] = 0;
  _$jscoverage['static_handler.js'][12] = 0;
  _$jscoverage['static_handler.js'][15] = 0;
  _$jscoverage['static_handler.js'][16] = 0;
  _$jscoverage['static_handler.js'][17] = 0;
  _$jscoverage['static_handler.js'][18] = 0;
  _$jscoverage['static_handler.js'][22] = 0;
}
_$jscoverage['static_handler.js'].source = ["/* Serves static files */","","var fs = require(\"fs\");","var ext = require(\"./ext\").ext;","","var STATIC_ROOT = __dirname + '/../../frontend/';","function serve_static(request, response, filename) {","\tfs.readFile(STATIC_ROOT + filename, function(err, data) {","\t\tif(err) {","\t\t\tresponse.writeHead(404);","\t\t\tresponse.end();","\t\t\treturn;","\t\t}","","\t\tvar content_type = ext.getContentType(ext.getExt(filename));","\t\tresponse.writeHead(200, {'Content-Type': content_type});","\t\tresponse.write(data);","\t\tresponse.end();","\t})","}","","exports.serve_static = serve_static;"];
_$jscoverage['static_handler.js'][3]++;
var fs = require("fs");
_$jscoverage['static_handler.js'][4]++;
var ext = require("./ext").ext;
_$jscoverage['static_handler.js'][6]++;
var STATIC_ROOT = (__dirname + "/../../frontend/");
_$jscoverage['static_handler.js'][7]++;
function serve_static(request, response, filename) {
  _$jscoverage['static_handler.js'][8]++;
  fs.readFile((STATIC_ROOT + filename), (function (err, data) {
  _$jscoverage['static_handler.js'][9]++;
  if (err) {
    _$jscoverage['static_handler.js'][10]++;
    response.writeHead(404);
    _$jscoverage['static_handler.js'][11]++;
    response.end();
    _$jscoverage['static_handler.js'][12]++;
    return;
  }
  _$jscoverage['static_handler.js'][15]++;
  var content_type = ext.getContentType(ext.getExt(filename));
  _$jscoverage['static_handler.js'][16]++;
  response.writeHead(200, {"Content-Type": content_type});
  _$jscoverage['static_handler.js'][17]++;
  response.write(data);
  _$jscoverage['static_handler.js'][18]++;
  response.end();
}));
}
_$jscoverage['static_handler.js'][22]++;
exports.serve_static = serve_static;
